# Generated by Django 4.2.3 on 2023-11-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneio', '0008_rename_is_expense_moneyinout_is_deductibles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyinout',
            old_name='is_deductibles',
            new_name='is_deductible',
        ),
    ]
