# Generated by Django 4.2.3 on 2023-11-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneio', '0009_rename_is_deductibles_moneyinout_is_deductible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_floating',
            field=models.BooleanField(),
        ),
    ]
